### ISSUE TITLE
(Java 8) BillingConnector.java - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by TBMSP** [moisoni97/google-inapp-billing#12]
En BillingConnector.java en la linea 277 se utiliza un método creado en Java 8 para comprobar duplicados en las IDs del SKU, el cual no es compatible con dispositivos que no cuenten con esta versión en su sistema, recomendaría usar otro método sin depender de Java 8.

Este error se produce en gran medida en dispositivos huawei, y celulares Android 6 e inferiores.

`Fatal Exception: java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at games.moisoni.google_iab.BillingConnector.connect(BillingConnector.java:277)
       at AppBilling.<init>(AppBilling.java:30)
       at MainActivity.onCreate(MainActivity.java:39)
       at android.app.Activity.performCreate(Activity.java:6279)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
       at android.app.ActivityThread.access$900(ActivityThread.java:163)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5585)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`

**Comment by TBMSP** [comment]
Una posible solución puede ser:


> //check for duplicates SKU ids
> Set<Integer> temperAllIdsSet = new HashSet<Integer>(temperAllIds);
> if (temperAllIds.size() != temperAllIdsSet.size()) {
> throw new IllegalArgumentException("The SKU id must appear only once in a list. Also, it must not be in different lists");
> }

`HashSet` no puede contener duplicados por lo que puede ser buena alternativa, y tambien puede usarse un `if` que comprueba la versión de android y utilizar este código solo para equipos más antiguos.

**Comment by moisoni97** [comment]
Hey, please write your issue in `English`.
Have you seen [this](https://github.com/moisoni97/google-inapp-billing#important-notice) in the `README`?
