### ISSUE TITLE
java.lang.NoClassDefFoundError V1.1.1

### ISSUE THREAD

**Issue by kimoandroid** [moisoni97/google-inapp-billing#49]
In Version 1.1.1 i've upgraded the billibg lib to V5 & the app worked but when i click on item & call the function ```billingConnector.purchase(payment.this, itemID)```
the app crashes,

this is the error log:

```java
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableList;
        at games.moisoni.google_iab.BillingConnector.purchase(BillingConnector.java:653)
        at games.moisoni.google_iab.BillingConnector.purchase(BillingConnector.java:628)

        at com.app.paym.payment$Gridview1Adapter.lambda$getView$0$com-app-paym-payment$Gridview1Adapter(payment.java:685)
        at com.app.paym.payment$Gridview1Adapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7498)
        at android.view.View.performClickInternal(View.java:7471)
        at android.view.View.access$3700(View.java:843)
        at android.view.View$PerformClick.run(View.java:29098)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8248)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

        Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &#34;com.google.common.collect.ImmutableList&#34; on path: DexPathList[[zip file &#34;/data/app/~~k-5sJaEvztbKcFitQEr0IA==/com.app.paym-w23RSv1-LySXb-MoSjy6fg==/base.apk&#34;],nativeLibraryDirectories=[/data/app/~~k-5sJaEvztbKcFitQEr0IA==/com.app.paym-w23RSv1-LySXb-MoSjy6fg==/lib/arm64, /system/lib64, /system_ext/lib64]]

        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 16 more
```

**Comment by moisoni97** [comment]
Hey,
Have you tried [this](https://github.com/moisoni97/google-inapp-billing#important-notice) from the `README`?

**Comment by kimoandroid** [comment]
Yes i've added all these and tried my app on Android 12 but this error appears.
he said that there is a missing class.

**Comment by moisoni97** [comment]
Show me your app's `build.gradle`...
Also, try adding this dependency `implementation 'com.google.guava:guava:31.1-android'` to see if it solves the missing `ImmutableList` class problem.

**Comment by kimoandroid** [comment]
> Show me your app's `build.gradle`... Also, try adding this dependency `implementation 'com.google.guava:guava:31.1-android'` to see if it solves the missing `ImmutableList` class problem.

ok, it worked now after adding guava lib.
thanks bro ❤


![Screenshot_1](https://user-images.githubusercontent.com/69405523/219945947-5b46f2c3-33cd-4b04-8716-c0dc5a98542c.png)

**Comment by moisoni97** [comment]
Ok, great!
Then I can close the issue now...
